#!/bin/bash

# install packages
sudo apt-get update
sudo apt-get install -y curl git
sudo apt-get install -y mongodb
sudo apt-get install -y nodejs npm
sudo ln -s /usr/bin/nodejs /usr/bin/node


pushd bogusAPI
sudo npm install
