#!/bin/bash

# install packages
sudo apt-get update
sudo apt-get install -y curl git
sudo apt-get install -y mongodb
sudo apt-get install -y nodejs npm
sudo ln -s /usr/bin/nodejs /usr/bin/node

sudo npm install -g gulp
sudo npm install -g bower

#MEAN
sudo npm install -g mean-cli

pushd bogusAPI
sudo npm install
